server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql.coffit.today:3306/oiljang
#    username: HIkdt6
#    password: HIkdt6

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oiljang
    username: ohgiraffers
    password: ohgiraffers

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB




#  security:
#    oauth2:
#      client:
#        registration:
#
#          naver:
#            client-id: Z3HB6zpnYOQfQxAReRdR
#            client-secret: fn4XxZnxRZ
#            redirect-uri: http://localhost:3306
#            authorization-grant-type: authorization_code
#            scope: name, email, profile_image
#            client-name: Naver
#
#          google:
#            client-id: 634314389152-hvham3k7rguk6i36b190d2adr0pi2ddb.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile, email
#
#
#        provider:
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response

jwt:
  secretKey : dkfjksjfdkls123kjakljksdfsd98798asd578a

  access:
    expiration: 3600000
#    header: Authorization
#
#  refresh:
#    expiration: 1209600000
#    header: Authorization-refresh


file:
  upload-dir: C:\Users\User\Desktop\dir\upload