server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.today:3306/oiljang
    username: HIkdt6
    password: HIkdt6

#  security:
#    oauth2:
#      client:
#        registration:
#
#          naver:
#            client-id: 클라이언트ID
#            client-secret: 클라이언트Secret
#            redirect-uri: 리다이렉트 url
#            authorization-grant-type: authorization_code
#            scope: name, email, profile_image
##            client-name: Naver
#
#          google:
#            client-id: 634314389152-hvham3k7rguk6i36b190d2adr0pi2ddb.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - profile
#              - email
#
#
#        provider:
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response

jwt:
  key: dkfjksjfdkls123kjakljksdfsd98798asd578a
  time: 9000000000