spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true
    database: mysql
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

